import type { VectorAny } from '../../shared/makeVectorElement';

export const ContainerTagNames = [
	'a',
	'defs',
	'g',
	'marker',
	'mask',
	'pattern',
	'svg',
	'switch',
	'symbol'
] as const satisfies readonly VectorAny['tagName'][];

export const GraphicsTagNames = [
	'circle',
	'ellipse',
	'image',
	'line',
	'path',
	'polygon',
	'polyline',
	'rect',
	'text',
	'use'
] as const satisfies readonly VectorAny['tagName'][];

export const RenderableTagNames = [
	'a',
	'circle',
	'ellipse',
	'foreignObject',
	'g',
	'image',
	'line',
	'path',
	'polygon',
	'polyline',
	'rect',
	'svg',
	'switch',
	'symbol',
	'text',
	'textPath',
	'tspan',
	'use'
] as const satisfies readonly VectorAny['tagName'][];

export const VectorTagNames = [
	'a',
	'animate',
	'animateMotion',
	'animateTransform',
	'circle',
	'clipPath',
	'defs',
	'desc',
	'ellipse',
	'feBlend',
	'feColorMatrix',
	'feComponentTransfer',
	'feComposite',
	'feConvolveMatrix',
	'feDiffuseLighting',
	'feDisplacementMap',
	'feDistantLight',
	'feDropShadow',
	'feFlood',
	'feFuncA',
	'feFuncB',
	'feFuncG',
	'feFuncR',
	'feGaussianBlur',
	'feImage',
	'feMerge',
	'feMergeNode',
	'feMorphology',
	'feOffset',
	'fePointLight',
	'feSpecularLighting',
	'feSpotLight',
	'feTile',
	'feTurbulence',
	'filter',
	'foreignObject',
	'g',
	'image',
	'line',
	'linearGradient',
	'marker',
	'mask',
	'metadata',
	'mpath',
	'path',
	'pattern',
	'polygon',
	'polyline',
	'radialGradient',
	'rect',
	'script',
	'set',
	'stop',
	'style',
	'svg',
	'switch',
	'symbol',
	'text',
	'textPath',
	'title',
	'tspan',
	'use',
	'view'
] as const satisfies readonly VectorAny['tagName'][];

export const CssGlobalValues = ['inherit', 'initial', 'revert', 'revert-layer', 'unset'] as const;
